/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "pvwlwiicsmfyogznqazm";
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2d2x3aWljc21meW9nem5xYXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzMzA5MDgsImV4cCI6MjA4MzkwNjkwOH0.2nVGaG5FtQbZDn6GmlMFjAYl71kaFkHiSMBjrNSA8ZE";
